//package com.impactrecipes;
//
//import com.impactrecipes.loader.ModsLoader;
//import cpw.mods.fml.common.Mod;
//import cpw.mods.fml.common.Mod.EventHandler;
//import cpw.mods.fml.common.ModMetadata;
//import cpw.mods.fml.common.event.FMLInitializationEvent;
//import cpw.mods.fml.common.event.FMLPostInitializationEvent;
//import cpw.mods.fml.common.event.FMLPreInitializationEvent;
//import cpw.mods.fml.common.event.FMLServerStartingEvent;
//
//import java.util.ArrayList;
//import java.util.Collections;
//import java.util.List;
//
//@Mod(
//        name = "Impact | Recipes Module",
//        version = "MC1710",
//        modid = ImpactRecipesModule.MODID,
//        dependencies = "required-after:Forge; after:impact; after:IC2; after:gregtech; after:tectech; after:EnderIO;"
//)
//public class ImpactRecipesModule {
//
//    public static final String MODID = "Impact|RecipesModule";
//    public static final String VERSION = "MC1710";
//    public static final String ASSET_PREFIX = "Impact|RecipesModule".toLowerCase();
//    public static final String TEXTURE_PATH = "Impact".toLowerCase();
//    public static List<Runnable> sPostInitRecipes = new ArrayList<>();
//
//    @Mod.Instance(MODID)
//    public static ImpactRecipesModule instance;
//
//    public ImpactRecipesModule() {
//    }
//
//    @EventHandler
//    public void init(FMLInitializationEvent event) {
//    }
//
//    @EventHandler
//    public void preInit(FMLPreInitializationEvent event) {
//    }
//
//    @EventHandler
//    public void postInit(FMLPostInitializationEvent event) {
//        ModsLoader.loader();
//    }
//
//    @EventHandler
//    public void serverStarting(FMLServerStartingEvent event) {
//    }
//
//    private void initModInfo(ModMetadata info) {
//        info.autogenerated = false;
//        info.modId = ASSET_PREFIX;
//        info.name = "Impact | Recipes Module";
//        info.version = VERSION;
//        info.description = "Module for Impact";
//        info.authorList = Collections.singletonList("Impact Team");
//    }
//}
